# Generated by Django 5.1.1 on 2024-09-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.ImageField(default='default.jpg', upload_to='gdata_image/')),
            ],
        ),
    ]
