# Generated by Django 5.1.1 on 2024-09-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataGame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdata',
            name='img',
            field=models.CharField(max_length=300),
        ),
    ]
