# Generated by Django 5.1.1 on 2024-09-07 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataGame', '0002_alter_gdata_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdata',
            name='id_game',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
