# Generated by Django 5.1.1 on 2024-09-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataGame', '0004_alter_gdata_id_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdata',
            name='id_game',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
