# Generated by Django 5.1.1 on 2024-10-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataGame', '0005_alter_gdata_id_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpicGdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SteamGdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_game', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('oprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('img', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Gdata',
        ),
    ]
